name: Deploy to Production with Ansible

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-to-production]

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          echo "${{ secrets.PRODUCTION_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i inventory/production.yml playbooks/deploy_production.yml --private-key private_key.pem -u '${{ secrets.PRODUCTION_USER }}' --extra-vars "PRODUCTION_HOST='${{ secrets.PRODUCTION_HOST }}' PRODUCTION_PORT='${{ secrets.PRODUCTION_PORT }}' PRODUCTION_DOMAIN='${{ secrets.PRODUCTION_DOMAIN }}' PRODUCTION_EMAIL='${{ secrets.PRODUCTION_EMAIL }}' ansible_become_pass='${{ secrets.PRODUCTION_PASSWORD }}'"
